I use this file to note installation steps and decisions I make when installing
and configuring Arch.

https://wiki.archlinux.org/title/installation_guide

* System Overview

** GRUB bootloader
** Booted in UEFI mode
** Busybox-based =initramfs= with the =encrypt= hook
** Partitions: =efi=,  =root= and =swap=
** Filesystem is =btrfs= (using the entirety of the =root= partition)
** Suspend-to-disk support (Work in progress!)
** Disk encryption of the =root= partition with passphrase
** Disk encryption of the =swap= partition with passphrase
*** We encrypt =swap= so that we can safely suspend (hibernate) to disk

* Steps

Check that our system is booted in 64-bit x64 UEFI mode:

#+begin_src bash
    $ cat /sys/firmware/efi/fw_platform_size
    64
#+end_src

Partition table:

#+begin_src bash
  /dev/sda1  300M       ef  EFI (FAT 32)
  /dev/sda2  1G         82  Linux swap   (encrypted)
  /dev/sda3  remaining  83  Linux        (encrypted)
#+end_src

Use use the recommended 300Mb for the UEFI partition. I tend to use 1Gb for swap
*in virtual machines*, and more (at least 2Gb) when installing on hardware.

* Disk Encryption

I use disk encruption with =passphrase= and only encrypt my root partion. I do not
encrypt my boot partition.

Load module =dm_crypt=:

#+begin_src bash
  $ modprobe dm_crypt
#+end_src

Format the encrypted container for =root= and then open it:

#+begin_src bash
  $ cryptsetup luksFormat --type luks2 --label=root /dev/sda3
  $ cryptsetup open /dev/sda3 root
#+end_src

Format the encrypted container for =swap= and then open it:

#+begin_src bash
  $ cryptsetup luksFormat --type luks2 --label=swap /dev/sda2
  $ cryptsetup open /dev/sda2 swap
#+end_src

Once opened, the root partition device address would be =/dev/mapper/root= instead
of the partition (e.g. =/dev/sda3=). The swap is =/dev/mapper/swap=. In order
to write encrypted data into the partition it must be accessed through
the device mapped name.

To close a LUKS container named "root" (unusual), unmount the partition and then
do:

#+begin_src bash
  $ cryptsetup close root
#+end_src

Make and format our filesystems. The UEFI partition must be FAT 32.

#+begin_src bash
  $ mkfs.fat -F 32 -n boot /dev/sda1
  $ mkswap -L swap /dev/mapper/swap
  $ mkfs.btrfs -L root /dev/mapper/root
#+end_src

Mount our partitions. The mount devices and compression argument will be used by
=genfstab= below... but of course we can still edit =/etc/fstab= later.

#+begin_src bash
  $ mount -o compress=zstd:3 /dev/mapper/root /mnt
  $ mount --mkdir /dev/sda1 /mnt/boot
  $ swapon /dev/mapper/swap
#+end_src

Bootstrap:

#+begin_src bash
  $ pacstrap -K /mnt base linux linux-firmware
#+end_src

Generate our =/etc/fstab= using labels (=-L=):

#+begin_src bash
  $ genfstab -L /mnt >> /mnt/etc/fstab
#+end_src

Verify that =/etc/fstab= is using only labels. Edit as required.

Before chrooting into our new system, let's create our =btrfs= subvolumes and set
them to mount. Here follow the [[https://wiki.archlinux.org/title/snapper#Suggested_filesystem_layout][suggest filesystem layout]] from the =snapper= wiki:

#+begin_src bash
  $ btrfs subvol create /mnt/@
  $ btrfs subvol create /mnt/@home
  $ btrfs subvol create /mnt/@.snapshots
  $ btrfs subvol create /mnt/@var_log
#+end_src

Add them to our =/etc/fstab=:

#+begin_src bash
  UUID=root  /            btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@            0  1
  UUID=root  /home        btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@home        0  0
  UUID=root  /.snapshots  btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@.snapshots  0  0
  UUID=root  /var/log     btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@var_log     0  0
#+end_src

The reason why I use =fs_passno= 0 (except for the /) is explained in more detail
here https://man.archlinux.org/man/fsck.btrfs.8.en

The sub-volume =@.snapshots= will be replaced below during snapper
configuration. Maybe we should avoid creating it here to evoid the extra work
later.

* Chrooted with =arch-chroot=

** Network

Install:

#+begin_src bash
  $ pacman -S networkmanager
#+end_src

Enable:

#+begin_src bash
  $ sysctl enable NetworkManager.service
#+end_src

** Initial ramdisk

Add =encrypt= to HOOKS in =/etc/mkinitcpio.conf= (after =udev,= and between =block= and
=filesystems=).

Because we use the busybox-based =initramfs= with the =encrypt= hook, we can decrypt
only a single partition at boot-time. We are required to create a =hook= in
=/etc/mkinitcpio.conf= to open the swap LUKS device before resuming from
hibernation and after botting.

Create =/etc/initcpio/hooks/openswap=:

#+begin_src bash
  run_hook ()
  {
    cryptsetup open /dev/sda2 swap
  }
#+end_src

Create =/etc/initcpio/install/openswap=:

#+begin_src bash
  build ()
  {
    add_runscript
  }

  help ()
  {
  cat<<HELPEOF
    This opens the swap encrypted partition /dev/sda2 in /dev/mapper/swap
  HELPEOF
  }
#+end_src

Add the hook =openswap= in the =HOOKS= array in =/etc/mkinitcpio.conf=, before
=filesystem= but after =encrypt=. Do not forget to add the =resume= hook after
=openswap=.

#+begin_src bash
  HOOKS=(... encrypt openswap resume filesystems ...)
#+end_src

Regenerate the =initramfs=:

#+begin_src bash
  $ mkinitcpio -P
#+end_src

** GRUB

Install =grub= and =efibootmgr=:

#+begin_src bash
  $ pacman -S grub efibootmgr
#+end_src

*Before* running =grubs='s installation script, set the default =btrfs= volume to be
the root of our filesystem so we don't have to pass it as a kernel argument:

Install =btrfs-progs= if needed.

#+begin_src bash
  $ btrfs subvol set-default 5 /
#+end_src

Run =grub='s installation script:

#+begin_src bash
  $ grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
#+end_src

Configure kernel arguments in =/etc/default/grub=. In my
=GRUB_CMDLINE_LINUX_DEFAULT= I add the following, using labels that we set when
creating the filesystems:

#+begin_src bash
  resume=LABEL=swap
  root=LABEL=root
  cryptdevice=LABEL=root:root
#+end_src

Refresh grub config file:

#+begin_src bash
  $ grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

The =mkconfig= will populate the Kernel argument =rootflags=subvol...= in
=/boot/grub/grub.cfg= with the btrfs default volume. See
https://bbs.archlinux.org/viewtopic.php?pid=1615373 for more.

** Users

At minimum, I install a user for myself.

#+begin_src bash
  $ useradd -m bruno
  $ passwd bruno
#+end_src

Add myself to sudoers:

#+begin_src bash
  $ gpasswd -a bruno whell
#+end_src

Configure =/etc/sudoers= to allow members of wheel to execute any command.

* Checks after first reboot

Swap status:

#+begin_src bash
  $ swapon --show
#+end_src

Internet connection:

#+begin_src bash
  $ ping archlinux.org
#+end_src

Root partition is encrypted (=TYPE=crypto_LUKS=):

#+begin_src bash
  $ blkid /dev/sda*
#+end_src

Filesystem is =btrfs= in our encrypted root:

#+begin_src bash
  $ btrfs filesystem show /dev/mapper/root
#+end_src

Our =btrfs= subvolumes:

#+begin_src bash
  $ btrfs subvol list /
#+end_src

Check our partitions and labels:

#+begin_src bash
  $ blkid
  $ lsblk -f
#+end_src

* Troubleshooting with an arch live cd

Boot from the cd.

Decrypt our root partition:

#+begin_src bash
  $ cryptsetup open /dev/sda3 root
#+end_src

Mount root and boot (assuming the EFI partition is =/dev/sda1=):

#+begin_src bash
  $ mount /dev/mapper/root /mnt
  $ mount /dev/sda1 /mnt/boot
#+end_src

Chroot:

#+begin_src bash
  $ arch-chroot /mnt
#+end_src

To exit:

#+begin_src bash
  $ exit
  $ umount -R /mnt
#+end_src

* Package management

I use [[https://github.com/Jguer/yay][yay]] as my AUR helper.

#+begin_src bash
  $ pacman -S --needed git base-devel
  $ git clone https://aur.archlinux.org/yay.git
  $ cd yay
  $ makepkg -si
#+end_src

Enable colored output by enabling =Color= in =/etc/pacman.conf=.

* Configuring snapshots

The packages I use are

- =snapper= :: Command-line program for filesystem snapshot management.
- =snap-pac= :: Pacman hooks that use snapper to create pre/post btrfs snapshots.
- =snapper-rollback= :: Python script to rollback btrfs systems.
- =grub-btrfs= :: Include btrfs snapshots in boot options.

The =snapper= package comes with two services that I use

- =snapper-timeline=
- =snapper-cleanup=

Create the configuration:

#+begin_src bash
  $ umount /.snapshots
  $ rm -rf /.snapshots
  $ snapper -c root create-config /
#+end_src

Because we created the =@.snapshots= sub-volume above, we follow [[https://wiki.archlinux.org/title/snapper#Configuration_of_snapper_and_mount_point][these extra steps
to replace it]].

From here, =snapper ls= should be working (probably under =sudo=).

Edit =/etc/snapper/configs/root=:

#+begin_src bash
  ALLOW_GROUPS="wheel"

  TIMELINE_LIMIT_HOURLY="5"
  TIMELINE_LIMIT_DAILY="7"
  TIMELINE_LIMIT_WEEKLY="0"
  TIMELINE_LIMIT_MONTHLY="0"
  TIMELINE_LIMIT_YEARLY="0"
#+end_src

Enable =grub-btrfs=,

#+begin_src bash
  $ systemctl start grub-btrfsd
  $ systemctl enable grub-btrfsd
#+end_src

And,

#+begin_src bash
  $ systemctl start snapper-timeline.timer
  $ systemctl enable snapper-timeline.timer
  $ systemctl start snapper-cleanup.timer
  $ systemctl enable snapper-cleanup.timer
#+end_src

* Rollback

https://wiki.archlinux.org/title/snapper#Restoring_/_to_its_previous_snapshot

#+begin_src bash
  $ cryptsetup open /dev/sda3 root
  $ mount -o subvolid=5 /dev/mapper/root /mnt
  $ mv /mnt/@ /mnt/home/bruno/@.broken{date}
  $ btrfs subvol snapshot /mnt/@.snapshots/{number}/snapshot /mnt/@
  $ umount -R /mnt
  $ mount -o subvol=@ /dev/mapper/root /mnt
  $ mount /dev/sda1 /mnt/boot
  $ arch-chroot /mnt
  $ grub-mkconfig -o /boot/grub/grub.conf
  $ mkinitcpio -P
  $ exit
  $ umount -R /mnt
#+end_src

Reboot.
