I use this file to note installation steps and decisions I make when installing
and configuring Arch.

https://wiki.archlinux.org/title/installation_guide

* System Overview

** GRUB bootloader
** Booted in UEFI mode
** Busybox-based =initramfs= with the =encrypt= hook
** Partitions: =efi=,  =root= and =swap=
** Filesystem is =btrfs= (using the entirety of the =root= partition)
** Suspend-to-disk support (Work in progress!)
** Disk encryption of the =root= partition with passphrase
** Disk encryption of the =swap= partition with passphrase
*** We encrypt =swap= so that we can safely suspend (hibernate) to disk

* Steps

Check that our system is booted in 64-bit x64 UEFI mode:

#+begin_src bash
    $ cat /sys/firmware/efi/fw_platform_size
    64
#+end_src

Partition table:

#+begin_src bash
  /dev/sda1  300M       ef  EFI (FAT 32)
  /dev/sda2  1G         82  Linux swap   (encrypted)
  /dev/sda3  remaining  83  Linux        (encrypted)
#+end_src

Use use the recommended 300Mb for the UEFI partition. I tend to use 1Gb for swap
*in virtual machines*, and more (at least 2Gb) when installing on hardware.

* Disk Encryption

I use disk encruption with =passphrase= and only encrypt my root partion. I do not
encrypt my boot partition.

Load module =dm_crypt=:

#+begin_src bash
  $ modprobe dm_crypt
#+end_src

Format the encrypted container for =root= and then open it:

#+begin_src bash
  $ cryptsetup luksFormat --label=root /dev/sda3
  $ cryptsetup open /dev/sda3 root
#+end_src

Format the encrypted container for =swap= and then open it:

#+begin_src bash
  $ cryptsetup luksFormat --label=swap /dev/sda2
  $ cryptsetup open /dev/sda2 swapDevice
#+end_src

Once opened, the root partition device address would be =/dev/mapper/root= instead
of the partition (e.g. =/dev/sda3=). The swap is =/dev/mapper/swapDevice=. In order
to write encrypted data into the partition it must be accessed through
the device mapped name.

To close a LUKS container named "root" (unusual), unmount the partition and then
do:

#+begin_src bash
  $ cryptsetup close root
#+end_src

Make and format our filesystems. The UEFI partition must be FAT 32.

#+begin_src bash
  $ mkfs.fat -F 32 -n boot /dev/sda1
  $ mkswap -L swap /dev/mapper/swapDevice
  $ mkfs.btrfs -L root /dev/mapper/root
#+end_src

Mount our partitions. The mount devices and compression argument will be used by
=genfstab= below... but of course we can still edit =/etc/fstab= later.

#+begin_src bash
  $ mount -o compress=zstd:3 /dev/mapper/root /mnt
  $ mount --mkdir /dev/sda1 /mnt/boot
  $ swapon /dev/mapper/swapDevice
#+end_src

Bootstrap:

#+begin_src bash
  $ pacstrap -K /mnt base linux linux-firmware
#+end_src

Generate our =/etc/fstab=:

#+begin_src bash
  $ genfstab -U /mnt >> /mnt/etc/fstab
#+end_src

Before chrooting into our new system, let's create our =btrfs= subvolumes and set
them to mount:

#+begin_src bash
  $ btrfs subvol create /mnt/@
  $ btrfs subvol create /mnt/@home
  $ btrfs subvol create /mnt/@.snapshots
  $ btrfs subvol create /mnt/@var_log
#+end_src

Add them to our =/etc/fstab=:

#+begin_src bash
  UUID=xyz  /            btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@            0  1
  UUID=xyz  /home        btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@home        0  0
  UUID=xyz  /.snapshots  btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@.snapshots  0  0
  UUID=xyz  /var/log     btrfs  rw,relatime,compress=zstd:3,space_cache=v2,subvol=@var_log     0  0
#+end_src

The reason why I use =fs_passno= 0 (except for the /) is explained in more detail
here https://man.archlinux.org/man/fsck.btrfs.8.en

* Chrooted with =arch-chroot=

** Network

Install:

#+begin_src bash
  $ pacman -S networkmanager
#+end_src

Enable:

#+begin_src bash
  $ sysctl enable NetworkManager.service
#+end_src

** Initial ramdisk

Add =encrypt= to HOOKS in =/etc/mkinitcpio.conf= (after =udev,= and between =block= and
=filesystems=).

Because we use the busybox-based =initramfs= with the =encrypt= hook, we can decrypt
only a single partition at boot-time. We are required to create a =hook= in
=/etc/mkinitcpio.conf= to open the swap LUKS device before resuming from
hibernation and after botting.

Create =/etc/initcpio/hooks/openswap=:

#+begin_src bash
  run_hook ()
  {
    cryptsetup open /dev/sda2 swapDevice
  }
#+end_src

Create =/etc/initcpio/install/openswap=:

#+begin_src bash
  build ()
  {
    add_runscript
  }

  help ()
  {
  cat<<HELPEOF
    This opens the swap encrypted partition /dev/sda2 in /dev/mapper/swapDevice
  HELPEOF
  }
#+end_src

Add the hook =openswap= in the =HOOKS= array in =/etc/mkinitcpio.conf=, before
=filesystem= but after =encrypt=. Do not forget to add the =resume= hook after
=openswap=.

#+begin_src bash
  HOOKS=(... encrypt openswap resume filesystems ...)
#+end_src

Regenerate the =initramfs=:

#+begin_src bash
  $ mkinitcpio -P
#+end_src

** GRUB

Install =grub= and =efibootmgr=:

#+begin_src bash
  $ pacman -S grub efibootmgr
#+end_src

*Before* running =grubs='s installation script, set the default =btrfs= volume to be
the root of our filesystem so we don't have to pass it as a kernel argument:

(Install =btrfs-progs= if needed.)

#+begin_src bash
  $ btrfs subvolume set-default 5 /
#+end_src

Run =grub='s installation script:

#+begin_src bash
  $ grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
#+end_src

Configure kernel arguments in =/etc/default/grub=. In my
=GRUB_CMDLINE_LINUX_DEFAULT= I add the following, using labels that we set when
creating the filesystems:

#+begin_src bash
  resume=LABEL=swap
  root=LABEL=root
  cryptdevice=LABEL=root:root
#+end_src

We can find the disk IDs with:

#+begin_src bash
  $ ls -l /dev/disk/by-id
#+end_src

Refresh grub config file:

#+begin_src bash
  $ grub-mkconfig -o /boot/grub/grub.cfg
#+end_src

* Checks after first reboot

Swap status:

#+begin_src bash
  $ swapon --show
#+end_src

Internet connection:

#+begin_src bash
  $ ping archlinux.org
#+end_src

Root partition is encrypted (=TYPE=crypto_LUKS=):

#+begin_src bash
  $ blkid /dev/sda*
#+end_src

Filesystem is =btrfs= in our encrypted root:

#+begin_src bash
  $ btrfs filesystem show /dev/mapper/root
#+end_src

Our =btrfs= subvolumes:

#+begin_src bash
  $ btrfs subvol list /
#+end_src

* Troubleshooting with an arch live cd

Boot from the cd.

Decrypt our root partition:

#+begin_src bash
  $ cryptsetup open /dev/sda3 root
#+end_src

Mount root and boot (assuming the EFI partition is =/dev/sda1=):

#+begin_src bash
  $ mount /dev/mapper/root /mnt
  $ mount /dev/sda1 /mnt/boot
#+end_src

Chroot:

#+begin_src bash
  $ arch-chroot /mnt
#+end_src

To exit:

#+begin_src bash
  $ exit
  $ umount -R /mnt
#+end_src
